import type { Metadata } from 'next'

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function LessonPageLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return <div className="relative p-6 w-full">{children}</div>
}
